package image

import (
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
	"testing"
)

func TestComponentsEnv(t *testing.T) {
	for _, c := range []struct {
		components Components
		want       []string
	}{
		{Components{}, []string{"AGENTBOX_WITH_ANDROID=0", "AGENTBOX_WITH_CODEX=0", "AGENTBOX_WITH_OPENCODE=0"}},
		{Components{Android: true}, []string{"AGENTBOX_WITH_ANDROID=1", "AGENTBOX_WITH_CODEX=0", "AGENTBOX_WITH_OPENCODE=0"}},
		{Components{Android: true, Codex: true}, []string{"AGENTBOX_WITH_ANDROID=1", "AGENTBOX_WITH_CODEX=1", "AGENTBOX_WITH_OPENCODE=0"}},
		{Components{OpenCode: true}, []string{"AGENTBOX_WITH_ANDROID=0", "AGENTBOX_WITH_CODEX=0", "AGENTBOX_WITH_OPENCODE=1"}},
	} {
		if got := c.components.Env(); !slices.Equal(got, c.want) {
			t.Errorf("Components%+v.Env() = %v, want %v", c.components, got, c.want)
		}
	}
	if got := (Components{}).Summary(); got != "no optional components" {
		t.Errorf("no components: %q", got)
	}
	if got := (Components{Android: true, Codex: true}).Summary(); got != "the Android tools and Codex" {
		t.Errorf("both components: %q", got)
	}
	if got := (Components{OpenCode: true}).Summary(); got != "OpenCode" {
		t.Errorf("OpenCode alone: %q", got)
	}
}

// The script has to agree with Options: every environment variable Env sends is
// one it reads, and each optional component is behind its own check.
func TestProvisionReadsTheOptions(t *testing.T) {
	script := string(provision)
	for _, env := range (Components{}).Env() {
		name, _, _ := strings.Cut(env, "=")
		if !strings.Contains(script, "${"+name+":-0}") {
			t.Errorf("provision.sh doesn't default %s to off", name)
		}
	}
	for _, want := range []string{
		`if [[ $WITH_ANDROID == 1 ]]; then`,  // scrcpy
		`if [[ $WITH_CODEX == 1 ]]; then`,    // the Codex CLI and its adapter
		`if [[ $WITH_OPENCODE == 1 ]]; then`, // the OpenCode CLI, its own adapter
	} {
		if !strings.Contains(script, want) {
			t.Errorf("provision.sh has no %q", want)
		}
	}
	// A pinned version is the point of pinning: nothing may ask for "latest".
	if strings.Contains(script, "@latest") || strings.Contains(script, "node@lts") {
		t.Error("provision.sh still installs an unpinned tool")
	}
}

// TestProvisionSwitchesToTheDebianMirror runs provision.sh's debian_from_mirror
// on a copy of the sources the Debian image comes with: Debian's own lines move
// to the mirror, the security archive stays where it is, and anything that
// isn't a web address is refused before it goes into a file apt reads.
func TestProvisionSwitchesToTheDebianMirror(t *testing.T) {
	script := string(provision)
	start := strings.Index(script, "debian_from_mirror() {")
	if start < 0 {
		t.Fatal("provision.sh has no debian_from_mirror")
	}
	end := strings.Index(script[start:], "\n}\n")
	if end < 0 {
		t.Fatal("debian_from_mirror has no end")
	}
	function := script[start : start+end+3]
	if !strings.Contains(script, `debian_from_mirror "$DEBIAN_MIRROR" /etc/apt/sources.list`) ||
		!strings.Contains(script, "${AGENTBOX_DEBIAN_MIRROR:-}") {
		t.Error("provision.sh doesn't switch to AGENTBOX_DEBIAN_MIRROR")
	}
	if strings.Index(script, "debian_from_mirror \"$DEBIAN_MIRROR\"") > strings.Index(script, "apt-get update") {
		t.Error("provision.sh switches to the mirror after it first uses apt")
	}

	const sources = "# Generated by distrobuilder\n" +
		"deb http://deb.debian.org/debian trixie main contrib\n" +
		"deb http://deb.debian.org/debian trixie-updates main contrib\n" +
		"deb http://deb.debian.org/debian-security/ trixie-security main contrib\n"
	cases := []struct {
		name, mirror, want string
		wantFail           bool
	}{
		{name: "a mirror", mirror: "http://debian.c3sl.ufpr.br/debian", want: "# Generated by distrobuilder\n" +
			"deb http://debian.c3sl.ufpr.br/debian trixie main contrib\n" +
			"deb http://debian.c3sl.ufpr.br/debian trixie-updates main contrib\n" +
			"deb http://deb.debian.org/debian-security/ trixie-security main contrib\n"},
		{name: "with a slash at the end", mirror: "https://mirror.example.org/debian/", want: "# Generated by distrobuilder\n" +
			"deb https://mirror.example.org/debian trixie main contrib\n" +
			"deb https://mirror.example.org/debian trixie-updates main contrib\n" +
			"deb http://deb.debian.org/debian-security/ trixie-security main contrib\n"},
		{name: "not a web address", mirror: "ftp.example.org/debian", wantFail: true},
		{name: "a second line smuggled in", mirror: "http://example.org/debian trixie main\ndeb http://evil.example", wantFail: true},
		{name: "sed's own characters", mirror: "http://example.org/debian|&", wantFail: true},
	}
	for _, c := range cases {
		f := filepath.Join(t.TempDir(), "sources.list")
		if err := os.WriteFile(f, []byte(sources), 0o644); err != nil {
			t.Fatal(err)
		}
		cmd := exec.Command("bash", "-c", "set -euo pipefail\n"+function+`debian_from_mirror "$1" "$2"`, "bash", c.mirror, f)
		out, err := cmd.CombinedOutput()
		got, _ := os.ReadFile(f)
		if c.wantFail {
			if err == nil || string(got) != sources {
				t.Errorf("%s: err %v, sources\n%s\nwant a failure and the sources untouched", c.name, err, got)
			}
			continue
		}
		if err != nil {
			t.Errorf("%s: %v\n%s", c.name, err, out)
		} else if string(got) != c.want {
			t.Errorf("%s: sources are\n%s\nwant\n%s", c.name, got, c.want)
		}
	}
}

func TestDownloadsFor(t *testing.T) {
	all := TotalMB(Downloads)
	plain := DownloadsFor(Components{})
	for _, d := range plain {
		if d.Option != "" {
			t.Errorf("a default build fetches %q, which is optional", d.Name)
		}
	}
	// The default build is the small one, and each option adds only its own.
	small, both := TotalMB(plain), TotalMB(DownloadsFor(Components{Android: true, Codex: true, OpenCode: true}))
	if both != all || small >= both {
		t.Errorf("totals: default %d MB, both options %d MB, everything %d MB", small, both, all)
	}
	if got := TotalMB(DownloadsFor(Components{Codex: true})); got <= small || got >= both {
		t.Errorf("with Codex only = %d MB, want between %d and %d", got, small, both)
	}
	if got := TotalMB(DownloadsFor(Components{OpenCode: true})); got <= small || got >= both {
		t.Errorf("with OpenCode only = %d MB, want between %d and %d", got, small, both)
	}

	// Every download says what it is and why, and every option is described.
	seen := map[string]bool{}
	for _, d := range Downloads {
		if d.Name == "" || !strings.HasSuffix(d.Purpose, ".") || d.MB <= 0 {
			t.Errorf("download %+v is incomplete", d)
		}
		if seen[d.Name] {
			t.Errorf("two downloads are called %q", d.Name)
		}
		seen[d.Name] = true
		if d.Option != "" && d.Option != OptionAndroid && d.Option != OptionCodex && d.Option != OptionOpenCode {
			t.Errorf("%q has the unknown option %q", d.Name, d.Option)
		}
	}
	for _, option := range []string{OptionAndroid, OptionCodex, OptionOpenCode} {
		if !slices.ContainsFunc(Downloads, func(d Download) bool { return d.Option == option }) {
			t.Errorf("no download belongs to the %q option", option)
		}
	}
}

func TestDownloadTable(t *testing.T) {
	table := DownloadTable(DownloadsFor(Components{}))
	if strings.Contains(table, "scrcpy") || strings.Contains(table, "Codex") || strings.Contains(table, "OpenCode") {
		t.Errorf("a default build's table offers optional components:\n%s", table)
	}
	if !strings.Contains(table, "Debian 13") || !strings.Contains(table, "Total") {
		t.Errorf("table is missing a row:\n%s", table)
	}
	for _, c := range [][2]string{{"999", "999 MB"}, {"1070", "1.1 GB"}, {"1343", "1.3 GB"}} {
		mb, _ := strconv.Atoi(c[0])
		if got := size(mb); got != c[1] {
			t.Errorf("size(%s) = %q, want %q", c[0], got, c[1])
		}
	}
}
